// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5fcZynOg9PzT1AvgGENqHj-JyJ9-0Ko',
    appId: '1:727313907190:web:95fcdaf8ec497908f71bd7',
    messagingSenderId: '727313907190',
    projectId: 'fir-three-9752f',
    authDomain: 'fir-three-9752f.firebaseapp.com',
    storageBucket: 'fir-three-9752f.firebasestorage.app',
    measurementId: 'G-HX0GZNYEZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdSczZQuv1VMmaaggarWdZItQyyRsuQY4',
    appId: '1:727313907190:android:5fce75c349244260f71bd7',
    messagingSenderId: '727313907190',
    projectId: 'fir-three-9752f',
    storageBucket: 'fir-three-9752f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91fxeXTQvPDg61J77mt-ruMOXWQh9UDE',
    appId: '1:727313907190:ios:3c66a91a4efb9b87f71bd7',
    messagingSenderId: '727313907190',
    projectId: 'fir-three-9752f',
    storageBucket: 'fir-three-9752f.firebasestorage.app',
    iosBundleId: 'com.example.firebase3',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91fxeXTQvPDg61J77mt-ruMOXWQh9UDE',
    appId: '1:727313907190:ios:3c66a91a4efb9b87f71bd7',
    messagingSenderId: '727313907190',
    projectId: 'fir-three-9752f',
    storageBucket: 'fir-three-9752f.firebasestorage.app',
    iosBundleId: 'com.example.firebase3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ5fcZynOg9PzT1AvgGENqHj-JyJ9-0Ko',
    appId: '1:727313907190:web:b1dec50036e31decf71bd7',
    messagingSenderId: '727313907190',
    projectId: 'fir-three-9752f',
    authDomain: 'fir-three-9752f.firebaseapp.com',
    storageBucket: 'fir-three-9752f.firebasestorage.app',
    measurementId: 'G-GCWTVBL8EC',
  );
}
