// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzbBKIWqx2khSKFTExeVLMANUzQlKw2Ps',
    appId: '1:620438430156:web:4b13ae6b05f99c5f53fd69',
    messagingSenderId: '620438430156',
    projectId: 'fir-two-e2687',
    authDomain: 'fir-two-e2687.firebaseapp.com',
    storageBucket: 'fir-two-e2687.firebasestorage.app',
    measurementId: 'G-FXGBPQY5NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5x9KdZyVF04gpWzqpjbtAIcslg84Nx7s',
    appId: '1:620438430156:android:8274310e5faef26153fd69',
    messagingSenderId: '620438430156',
    projectId: 'fir-two-e2687',
    storageBucket: 'fir-two-e2687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyn48GPsyDutvIbV33xzX_w9UB5SJaOsU',
    appId: '1:620438430156:ios:caf4bfd6e434100953fd69',
    messagingSenderId: '620438430156',
    projectId: 'fir-two-e2687',
    storageBucket: 'fir-two-e2687.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyn48GPsyDutvIbV33xzX_w9UB5SJaOsU',
    appId: '1:620438430156:ios:caf4bfd6e434100953fd69',
    messagingSenderId: '620438430156',
    projectId: 'fir-two-e2687',
    storageBucket: 'fir-two-e2687.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzbBKIWqx2khSKFTExeVLMANUzQlKw2Ps',
    appId: '1:620438430156:web:c233998081b43bfd53fd69',
    messagingSenderId: '620438430156',
    projectId: 'fir-two-e2687',
    authDomain: 'fir-two-e2687.firebaseapp.com',
    storageBucket: 'fir-two-e2687.firebasestorage.app',
    measurementId: 'G-YE81HHE908',
  );
}
